/**
 * Icinga2 API Configuration
 * For SaltStack integration and automation
 */

object ApiListener "api" {
  accept_commands = true
  accept_config = true
  
  ticket_salt = "{{ pillar['secrets']['icinga_ticket_salt'] }}"
}

object ApiUser "{{ api_user }}" {
  password = "{{ api_pass }}"
  permissions = [ "*" ]
}
